#!/bin/sh

### BEGIN INIT INFO
# Provides:          apnsagent
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts apnsagent system
# Description:       starts apnsagent using basic start scripts
### END INIT INFO

PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=apnsagent
DAEMON=/usr/local/bin/apnsagent-server.py
DESC=apnsagent

OWNER=apns

test -x $DAEMON || exit 0

set -e

DAEMON_OPTS="/opt/config/apnsagent/conf"

case "$1" in
  start)
        echo -n "Starting $DESC: "
	start-stop-daemon --start --background --chuid $OWNER:$OWNER --user $OWNER \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
       	echo -n "Stopping $DESC: "
	start-stop-daemon --signal 3 --user $OWNER --quiet --retry 2 --stop \
		--exec $DAEMON
	echo "$NAME."
	;;

      *)    
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop}" >&2
            exit 1
            ;;
    esac
    
    exit 0
